### ISSUE TITLE
recidive jail not working with -vv

### ISSUE THREAD

**Issue by xolom** [linuxserver/docker-fail2ban#10]
Execution of `fail2ban-client` with argument `-vv` results in different log output formatting and therefore `recidive` jail doesn't work as expected.

My workaround was a custom Dockerfile:
```Dockerfile
FROM linuxserver/fail2ban:latest

RUN sed -i 's/ -vv//g' /etc/s6-overlay/s6-rc.d/svc-fail2ban/run
```

**Comment by nemchik** [comment]
Looking at https://github.com/linuxserver/fail2ban-confs/blob/master/filter.d/recidive.conf it seems its purpose is something similar to [incremental banning](https://github.com/linuxserver/fail2ban-confs/tree/master#incremental-banning).

I am a bit hesitant to remove the verbosity as it can be very useful when troubleshooting.

**Comment by nemchik** [comment]
I'll add something to adjust verbosity.

**Comment by nemchik** [comment]
This should be solved by https://github.com/linuxserver/docker-fail2ban/pull/17

We'll allow users to specify whatever verbosity they prefer for the container log output.
