### ISSUE TITLE
[BUG] nginx-unauthorized fails

### ISSUE THREAD

**Issue by Xeroxxx** [linuxserver/docker-fail2ban#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fail2Ban loops within the container when you enable nginx-unauthorzed.

```
 ['start', 'nginx-unauthorized']]] has failed. Received RegexException("Unable to compile regular expression '.*(?i)plex.*':\nglobal flags not at the start of the expression at position 2")
 2023-05-28 18:49:20,262 FFFF8B868B20 ERROR NOK: ("Unable to compile regular expression '.*(?i)plex.*':\nglobal flags not at the start of the expression at position 2",)
```

```
2023-05-28 18:49:20,258 FFFF8CAA4060 ERROR Unable to compile regular expression '.*(?i)plex.*':
global flags not at the start of the expression at position 2
```

Editing and commenting the string, results in a replacement and loop again.

Workaroud start container and edit nginx-unauthorrized conf.

### Expected Behavior

Running and not looping.

### Steps To Reproduce

Enable jail for nginx-unauthorized

### CPU architecture

x86-64

### Docker creation

```bash
docker compose as documentation uses.
```

### Container logs

```bash
See above.
```

**Comment by Dilomos** [comment]
I don't think this is related to nginx-unauthorrized default conf
but i face similar issue since i've updated to last fail2ban docker image
it appear that any regex containing ".*(?i)" fail with that same error
i have a couple that all trigger the same issue 
            ^<HOST> -.*"(GET|POST|HEAD) (?i)(/autodiscover).*"$
            ^<HOST> -.*"(GET|POST|HEAD) (?i)(/hnap)*"$
I don't know what has changed in regex parsing but this is an issue
