### ISSUE TITLE
[BUG] Mails : msmtp parameters ?

### ISSUE THREAD

**Issue by MuadDibVV** [linuxserver/docker-fail2ban#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

  When trying to receive an email to trace event I have an error message

sendmail: can't connect to remote host (127.0.0.1): Connection refused

How can we configure msmtp on this container ?

### Expected Behavior

A mail should be send

### Steps To Reproduce

Just activate the mail on action

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
Using the docker compose proposed
```

### Container logs

```bash
2023-08-28 20:01:41,624 7F309B693B38 ERROR 7f309c69d170 -- exec: printf %b "Subject: [Fail2Ban] service: started on Server
Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
From: Fail2Ban <monemail@domaine.fr>
To: monemail@domaine.fr\n
Hi,\n
The jail service has been started successfully.\n
Regards,\n
Fail2Ban" | /usr/sbin/sendmail -f "monemail@domaine.fr" "monemail@domaine.fr"
 2023-08-28 20:01:41,624 7F309B693B38 ERROR 7f309c69d170 -- stderr: "sendmail: can't connect to remote host (127.0.0.1): Connection refused"
 2023-08-28 20:01:41,625 7F309B693B38 ERROR 7f309c69d170 -- returned 1
 2023-08-28 20:01:41,625 7F309B693B38 ERROR Failed to start jail 'service' action 'sendmail-whois': Error starting action Jail('service')/sendmail-whois: 'Script error'
```

**Comment by j0nnymoe** [comment]
Sendmail isn't included with the container, you need to edit the config to use a remote SMTP server.

**Comment by nemchik** [comment]
Correction:
`sendmail` IS included in our fail2ban image. `msmtp` is not included, but can be added using our [universal package install](https://github.com/linuxserver/docker-mods/tree/universal-package-install) mod.

`sendmail` should be configurable by mounting a volume for `/etc/mail/` and creating a `sendmail.cf` and/or `sendmail.mc` (there may be other required files, you would need to look up sendmail configuration).

**Comment by MuadDibVV** [comment]
Thank you for your answers.
After analyse I just have to add an env variable "SMTPHOST=smtp.domaine" to use it.
It should be interesting to precise it on the read me part.
