### ISSUE TITLE
[FEAT] <wordpress support>

### ISSUE THREAD

**Issue by nivepl** [linuxserver/docker-fail2ban#28]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Basically the title. Was wondering why wordpress is not included in supported apps.

### Reason for change

Most attacks come from wordpress probing imo

**Comment by drizuid** [comment]
`Basically the title. Was wondering why wordpress is not included in supported apps.` that is a question for fail2ban, not us. we just package their stuff. You're welcome and encouraged to create your own local confs to handle whatever you need.
